#docker-compose.yml (Base)
version: "3.9"
services:
  db:
    image: "postgres:14.5"
    container_name: fk_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=fk
  mysql-test:
    image: "mysql:8.0"
    container_name: mysql_test
    restart: always
    ports:
      - "3310:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testbulk